### ISSUE TITLE
#include "platform/scratch_buffer.hpp": No such file or directory.

### ISSUE THREAD

**Issue by BenjaminGu** [evanbowman/blind-jump-portable#10]
I tried to build this project using CMake and Visual studio.
However, I got the following error message.

> Error	C1083	Cannot open include file: 'platform/scratch_buffer.hpp': No such file or directory	BlindJump	 

Where can I find scratch_buffer.hpp?

**Comment by evanbowman** [comment]
Sorry, you're right, I forgot to commit the file. I just fixed the issue on the master branch.

**Comment by evanbowman** [comment]
https://github.com/evanbowman/blind-jump-portable/commit/b17f5bef5f88d0bb18ba13bb4da7dba03858aef5

**Comment by evanbowman** [comment]
Also, I have not written any instructions for how to compile the desktop version of the game with visual studio. Visual Studio cannot cross compile for ARM/MIPS architectures as far as I know, so I'm assuming you're trying to compile the game for microsoft windows, not gba or psp.

**Comment by evanbowman** [comment]
I personally have compiled the game for desktop windows PCs, so it's possible, but I remember some of the steps being a bit difficult.

**Comment by BenjaminGu** [comment]
thank you. I just compiled this project successfully for Windows PC.
