### ISSUE TITLE
PSP Version?

### ISSUE THREAD

**Issue by ptnnx** [evanbowman/blind-jump-portable#12]
Where is psp version 
I don't find?

**Comment by evanbowman** [comment]
The source code for the PSP version can be found here: https://github.com/evanbowman/blind-jump-portable/blob/master/source/platform/psp/psp_platform.cpp

I do not post release ROMs for the PSP version yet, because I haven't finished programming the sound, so there is no audio.

**Comment by ptnnx** [comment]
Ok
