### ISSUE TITLE
Unbalanced with "Non-commercial use only" text

### ISSUE THREAD

**Issue by LoveBodhi** [evanbowman/blind-jump-portable#14]
This only appears if you choose "Chinese" language, and this doesn't appear in English.

**Comment by evanbowman** [comment]
The translator told me that piracy was sometimes a problem in his country, so I added the non-commercial text, to protect users from being tricked into buying a free game. The text is mainly there to protect users. I would prefer not to need to include the non-commercial text in any of the game's language modes, as I think that the text looks a bit unsightly.

**Comment by evanbowman** [comment]
I could add similar text to the english version I guess, if people are unhappy about this.
