### ISSUE TITLE
Translate this project to German

### ISSUE THREAD

**Issue by psjnek** [evanbowman/blind-jump-portable#23]
This project hasn't been active in years but I wanted to ask anyway if you would like me to translate this project to German. 
Thank you very much for creating such a beautiful open-source game.

WebSnke

**Comment by evanbowman** [comment]
Thank you for your interest in the project! I'm not actively working on this anymore, but I can help you add a new translation if you want to contribute one. Adding a translation shouldn't be too much work, mainly we'd just need to add a new strings file. The difficulty in adding translations mainly results from the GBA's limited screen size and getting translated text to fit correctly. I've heard German has a lot of long words :)

**Comment by psjnek** [comment]
In German, nouns begin with a capital letter. Should I just the same letter case as in the English version (for artistic reasons) or use the German one?

**Comment by psjnek** [comment]
What exactly does "Worker's notebook" mean?
Is it a notebook of a worker or a notebook designed for workers?

**Comment by evanbowman** [comment]
I would use a capital letter if that's what German speakers would be most comfortable with.
A notebook of a worker.

**Comment by WebSnke** [comment]
Should I change feet to meter as we don't use the imperial system?
