### ISSUE TITLE
Restore license headers to external files

### ISSUE THREAD

**Issue by AntonioND** [evanbowman/blind-jump-portable#5]
I've just noticed that you have taken a few files out of libgba and just removed the license header that credits the authors and specifies the conditions to use the files:

https://github.com/evanbowman/blind-jump-portable/blob/76caaa9ee72121cbae535db7639c76f1264a14b0/source/platform/gba/interrupt_dispatch.s
https://github.com/evanbowman/blind-jump-portable/blob/76caaa9ee72121cbae535db7639c76f1264a14b0/source/platform/gba/bios_math.s
https://github.com/evanbowman/blind-jump-portable/blob/76caaa9ee72121cbae535db7639c76f1264a14b0/source/platform/gba/reset.s

Original files:

https://github.com/devkitPro/libgba/blob/3751d012eb5a9d60b172d1ec2a9b581136d389c5/src/InterruptDispatcher.s
https://github.com/devkitPro/libgba/blob/3751d012eb5a9d60b172d1ec2a9b581136d389c5/src/Div.s
https://github.com/devkitPro/libgba/blob/3751d012eb5a9d60b172d1ec2a9b581136d389c5/src/Reset.s

Also, you've got code from libtonc:

https://github.com/evanbowman/blind-jump-portable/blob/76caaa9ee72121cbae535db7639c76f1264a14b0/source/platform/gba/memcpy.s

Original file:

https://github.com/devkitPro/libtonc/blob/ccc03fa321e56f51aed5e2ee1d6e3df3d1cbc803/asm/tonc_memcpy.s

Please, restore the headers, and do the same to other files if you have removed their headers. And, if you modify them, specify so below the original header.

**Comment by evanbowman** [comment]
It's not exactly that I copied the files and removed the licenses, you'll notice that some of the files don't even have the same names. I didn't want to have to link to the libgba library just for these files, and I copied the assembly instructions into these files, and probably didn't bother to copy the comment block at the top of the file. Now that I look at this licensing, does this mean that I need to convert this project to gpl, or just make the project open source, as I'm already doing?

P.s. Tonc, along with devkit arm, are specifically credited in the special thanks section of the in-game credits, I'm not trying to steal credit for other people's work. https://github.com/evanbowman/blind-jump-portable/blob/master/source/state/endingCreditsState.cpp#L67

**Comment by AntonioND** [comment]
Yeah, the files don't have the same names, but the content is the same. I understand not wanting to link with libgba just for 2 or 3 files, to be honest, but the fix is really easy in this case.

libgba is LGPL. I'm not sure how it works when you link it statically, to be fair. The thing is, your game is MIT, which is less restrictive than LGPL, so all you have to do is keep it as it is, open source, and restore the headers.

Giving credit is nice, but if the files don't have the right copyright, whoever copies them from your game doesn't know where they came from or the license they have, and they may assume they are MIT-licensed.

EDIT: libtonc is MIT-licensed as well, even though that's not as clear. https://github.com/devkitPro/libtonc/pull/4

**Comment by evanbowman** [comment]
Ah I see, just a minute, I'll fix the files.

**Comment by evanbowman** [comment]
Actually, I don't even think that I'm using any of the code from bios_math.s, at first I thought that these math routines from the bios were actually faster than the emulated division from devkitarm compiler, but turns out that there isn't really any significant difference, and in some cases, the compiler can optimize the emulated division better, because it has no concept really of what the assembly instructions in the bios look like.

**Comment by evanbowman** [comment]
I'll add the licences everywhere for now, and remove unused files later.

**Comment by evanbowman** [comment]
Ok, I added back the licenses. For memcpy.s, which never had a license attached to the file in the first place, I inserted the licence, from the PR that you linked, at the top of the file. Let me know if this is acceptable.

https://github.com/evanbowman/blind-jump-portable/blob/master/source/platform/gba/memcpy.s

**Comment by AntonioND** [comment]
Works for me.

**Comment by evanbowman** [comment]
Cool, thanks for your suggestions.
